### ISSUE TITLE
Shell scripts in 2.3.3 broken

### ISSUE THREAD

**Issue by damphyr** [oneclick/rubyinstaller#355] opened 2017-02-21 11:03 UTC
Just stumbled over this:  When using the 2.3.3 installer and setting it in the path rake invocation fails in git bash with 

```
$ rake -T
bash: /c/tools/ruby/bin/rake: C:/Users/Justin/Projects/rubyinstaller/sandbox/ruby23_mingw/bin/ruby.exe: bad interpreter: No such file or directory
``` 
Looks like Justin built this on his own machine :).
Huge kudos for the work, but while the batch file wrappers work, all built-in shell wrappers are broken. Unfortunately, Windows now sometimes has a bash as well :(

**Comment by damphyr** [comment] 2017-02-21 11:06
With ruby in the PATH replacing all #! with 
```
#!ruby.exe
```
provides a workaround.

**Comment by Azolo** [comment] 2017-04-17 20:50
Duplicate of #317

**Closed by Azolo** 2017-04-17 20:50 UTC
