### ISSUE TITLE
compiling local source 2.2 failed

### ISSUE THREAD

**Issue by xcjiang** [oneclick/rubyinstaller#329] opened 2016-07-07 11:33 UTC
I compiled ruby 2.2 by using my local source, but it failed every time.
I use the following command:

`rake ruby22 DKVER=mingw64-32-4.7.2 LOCAL="d:/ruby/ruby_2_2" `

the final part of ouput is:
```
make[1]: Entering directory `/d/workspace/ruby/rubyinstaller/sandbox/ruby22_build'
make[2]: Entering directory `/d/workspace/ruby/rubyinstaller/sandbox/ruby22_build/ext/-test-/array/resize'
generating resize-i386-mingw32.def
compiling ../../../../../../../ruby_2_2/ext/-test-/array/resize/resize.c
linking shared-object -test-/array/resize.so
Cannot export -e: symbol not defined
Cannot export fname:: symbol not defined
collect2.exe: error: ld returned 1 exit status
make[2]: *** [../../../../.ext/i386-mingw32/-test-/array/resize.so] Error 1
make[2]: Leaving directory `/d/workspace/ruby/rubyinstaller/sandbox/ruby22_build/ext/-test-/array/resize'
make[1]: *** [ext/-test-/array/resize/all] Error 2
make[1]: Leaving directory `/d/workspace/ruby/rubyinstaller/sandbox/ruby22_build'
make: *** [build-ext] Error 2
rake aborted!
Command failed with status (2): [make  all...]
```

I can successfully build with this:
`rake ruby22 DKVER=mingw64-32-4.7.2`

my local source code is identical with the source downloaded by rubyinstaller.

build env:
win7 x64
ruby 2.2.4

**Comment by golirev** [comment] 2016-07-09 13:46
@xcjiang

I can't reproduce your compile failure.
When I run the build script on Window's Command Prompt with your directory structure.
I got below output.

```
make[1]: Entering directory `/f/workspace/ruby/rubyinstaller/sandbox/ruby22_build'
make[2]: Entering directory `/f/workspace/ruby/rubyinstaller/sandbox/ruby22_build/ext/-test-/array/resize'
generating resize-i386-mingw32.def
compiling ../../../../../../../../../ruby/ruby_2_2/ext/-test-/array/resize/resize.c
linking shared-object -test-/array/resize.so
make[2]: Leaving directory `/f/workspace/ruby/rubyinstaller/sandbox/ruby22_build/ext/-test-/array/resize'
make[2]: Entering directory `/f/workspace/ruby/rubyinstaller/sandbox/ruby22_build/ext/-test-/bignum'
generating bignum-i386-mingw32.def
compiling ../../../../../../../../ruby/ruby_2_2/ext/-test-/bignum/big2str.c
```

I don't know why the output is different about relative path.

My result is from the following.

### RubyInstaller
 (on Git-Bash propmpt)
  cd /f/workspace/ruby
  git clone https://github.com/oneclick/rubyinstaller.git rubyinstaller

### Build Command
(on Window's Command Prompt )
#### 1st build:
  F:
  cd F:\workspace\ruby\rubyinstaller
  rake ruby22  DKVER=mingw64-32-4.7.2 TMP=f:\temp

#### copy ruby_2_2 directory using 7zip to follow your directory structure:
  F:\workspace\ruby\rubyinstaller\sandbox\ruby_2_2
    to
  F:\ruby\ruby_2_2
  (The contents of the directory are ruby-2.2.4.tar.bz2.)

#### 2nd build:
  F:
  cd F:\workspace\ruby\rubyinstaller
  rake clean
  rake ruby22  LOCAL="F:/ruby/ruby_2_2" DKVER=mingw64-32-4.7.2 TMP=f:\temp

### build env
  win10 x64
  ruby 2.2.4

**Comment by Azolo** [comment] 2016-07-19 19:56
I can't reproduce it either. =/

Gonna close this, if you can give more information about what's going on I'll open this back up.

**Closed by Azolo** 2016-07-19 19:56 UTC
