### ISSUE TITLE
Ruby 2.3.1p112 and Gem 2.5.1 throwing SSL Error

### ISSUE THREAD

**Issue by predatorian3** [oneclick/rubyinstaller#337] opened 2016-10-06 14:04 UTC
Recently installed the DevKit and Ruby 2.3.1 provided by the rubyinstaller.org website, and I ran into an SSL issue. I'm also using Cmder with git-for-windows 1.8

```
C:\Users\USER01
λ ruby -v
ruby 2.3.1p112 (2016-04-26 revision 54768) [x64-mingw32]

C:\Users\USER01
λ gem -v
2.5.1

C:\Users\USER01
λ where ruby
C:\tools\ruby23\bin\ruby.exe

C:\Users\USER01
λ where gem
C:\tools\ruby23\bin\gem
C:\tools\ruby23\bin\gem.cmd

C:\Users\USER01
λ gem install vault
ERROR:  Could not find a valid gem 'vault' (>= 0), here is why:
          Unable to download data from https://rubygems.org/ - SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (https://api.rubygems.org/specs.4.8.gz)

C:\Users\USER01
λ gem install bundler
ERROR:  Could not find a valid gem 'bundler' (>= 0), here is why:
          Unable to download data from https://rubygems.org/ - SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (https://api.rubygems.org/specs.4.8.gz)

```

**Comment by david-rui** [comment] 2016-10-06 17:44
Check the solution here: https://github.com/oneclick/rubyinstaller/issues/324

Regards

**Comment by Azolo** [comment] 2016-10-06 20:30
Duplicate of #338, though the #324 link is useful.

**Closed by Azolo** 2016-10-06 20:30 UTC
