### ISSUE TITLE
Installer 2.4.1-2-x64 does not have Tk

### ISSUE THREAD

**Issue by ParadoxV5** [oneclick/rubyinstaller#373] opened 2017-08-03 01:31 UTC
The Installer 2.4.1-2-x64 does not have Tk as previous versions (? - I just read from TkDocs which said that Tk should be in the Installers) does. Neither it will be installed nor there is an option for that.
![screenshot_20170802193059](https://user-images.githubusercontent.com/30676755/28901969-29305e92-77b9-11e7-9ff9-a3dcf0d59e93.png)

**Comment by Azolo** [comment] 2017-08-03 01:57
Duplicate of #371

**Closed by Azolo** 2017-08-03 01:57 UTC
