### ISSUE TITLE
Ruby 2.1.6 (x64) installer issue in windows 10

### ISSUE THREAD

**Issue by pli88** [oneclick/rubyinstaller#286] opened 2015-08-23 06:41 UTC
When tried installing windows wait icon shows up for some secs and nothing proceeds further. 

PS :  Ruby 2.2.2 (x64) worked fine in windows 10

**Comment by Azolo** [comment] 2015-08-23 13:19
Duplicate of #282, check out the discussion there and leave feedback.

Thank you!

**Closed by Azolo** 2015-08-23 13:19 UTC
