### ISSUE TITLE
Delegating maintenance and releases of RubyInstaller

### ISSUE THREAD

**Issue by Azolo** [oneclick/rubyinstaller#255] opened 2015-01-21 21:28 UTC
With @luislavena no longer actively maintaining RubyInstaller, I'm going to take over the release schedule and other relevant issues.

The process requires transfer of outside credentials, among other things.

This issue is to keep track of the process and hopefully help document it.

**Comment by luislavena** [comment] 2015-01-21 23:48
Hello @Azolo thanks for starting this thread.

The following are the items I believe needs to be addressed for each part
of the project:

## RubyInstaller

- [x] GitHub: Grant permissions as *Owner* of the org (Luis)
- [ ] Site: Create website login credentials (Luis)
- [ ] Heroku: Create account and inform email used (Azolo)
- [ ] Heroku: Grant contributor/collaborator permissions (Luis)
- [ ] Bintray: Create account and inform username/email (Azolo)
- [ ] Bintray: Grant permissions to user (Luis)
- [ ] S3 credentials (for CloudFront/CDN)

## knapsack (and openknapsack.org packages)

- [ ] S3 credentials (for uploading)

RubyInstaller email is managed by Google Apps.

Domains rubyinstaller.org and openknapsack.org are managed via Namecheap and
been paid until 2019 and 2016 respectively.

DNS is managed via CloudFlare (free account) with rubyinstaller.org email

Ideally, all S3 related material should be moved to a different place,
probably usage of bintray accounts and upload of multiple releases/packages.

I think the next steps will be:

- Signup to Heroku for addition as collaborator
- Setup a bintray account and grant permissions to your user
- Ensure you can push by uploading old releases (accessible via the CDN)
- Move knapsack packages to bintray
- Move remaining old releases of RubyInstaller to bintray

But all those steps can be later done by you.

At this time, S3/CloudFront cost me around 100 USD/month, which is something
I can maintain for a few more months but would like to migrate if possible.

Let me know what email address/username would you like to use to manage the website, and what email address will be used for Heroku.

Cheers.

**Comment by Azolo** [comment] 2015-01-23 00:15
Alright, I've sent you an email with management information.

Is there anything left on S3/Cloudfront if we upload all the previous releases plus knapsack packages to Bintray?

**Comment by luislavena** [comment] 2015-01-23 22:31
> I've sent you an email with management information.

Replied, waiting on bintray acceptance of invite so can grant you permissions.

> Is there anything left on S3/Cloudfront if we upload all the previous releases...

Just DevKit releases. Those could be added to bintray too.

Cheers.

**Comment by luislavena** [comment] 2015-01-24 00:08
@Azolo permissions granted on Bintray!

Cheers.

**Comment by Azolo** [comment] 2015-02-16 22:52
Alright, I've uploaded all the previous releases of RubyInstaller and the DevKits to Bintray.

Still need to get all the knapsack packages though.

**Comment by luislavena** [comment] 2015-02-17 01:04
@Azolo awesome!

I'm sending you now the S3 credentials to access the knapsack bucket so you don't need to hunt down every single release.

Cheers.

**Comment by luislavena** [comment] 2015-02-17 11:28
@Azolo delivered S3 credentials for openknapsack packages and distfiles.

If you're using CloudBerry Explorer you will need to enter `distfiles.openknapsack.org` or `packages.openknapsack.org` manually in the location bar.

This is caused by S3 not returning the buckets you have permissions when requesting `ListAllBuckets` (even when you have them).

Let me know if you can access it.

Cheers.

**Comment by Azolo** [comment] 2015-02-18 22:34
Ok, packages are uploaded. 
There were some `distfiles` without packages. I didn't upload those.

https://bintray.com/oneclick/OpenKnapsack

I'll start doing the work on changing the RubyInstaller and Knapsack recipes soon, plus making announcements. Probably get more information on the package `README`s etc.

I think the issue I'm going to have trouble with now is: I don't know how the cms for rubyinstaller.org currently works.

**Comment by luislavena** [comment] 2015-02-18 23:25
@Azolo great!

> There were some distfiles without packages. I didn't upload those.

Yeah, some source packages were uploaded for testing some recipes, but never *made* into packages.

> I think the issue I'm going to have trouble with now is: I don't know how the cms for rubyinstaller.org currently works.

Is a Radiant CMS, you edit the HTML files via the web :cry: 

I can put you in touch with the developer who started to work on making the web pusheable, perhaps convert it to Jekyll:

https://github.com/oneclick/rubyinstaller.org

**Comment by Azolo** [comment] 2015-03-05 21:29
@luislavena Alright.

So, all of the download links on rubyinstaller.org have been changed and point to their respective Bintray links.
There were a few casualties of really old/experimental releases I couldn't get my hands on, but otherwise things look good there.

As for the cdn, there are still some static assets being served as part of rubyinstaller.org.
Once we take a look at those and get that figured out I think we can look at how to handle any redirects that may need to be done.

On another note, when I released Ruby 2.2.1 today the [results of `make check`][1] weren't looking great. What's the best way to report this kind of stuff?

[1]: https://gist.github.com/Azolo/442a4dfdd259986d043d

**Comment by luislavena** [comment] 2015-03-05 21:33
> So, all of the download links on rubyinstaller.org have been changed and point to their respective Bintray links.

Awesome! :heart: :sparkles: :sparkling_heart: 

> As for the cdn, there are still some static assets being served as part of rubyinstaller.org.

:+1: roger that, I think those static assets will go away if you pursue the site redesign. If not, I think can be added to the app of the site itself and the html/css/js corrected.

> On another note, when I released Ruby 2.2.1 today the results of make check weren't looking great. What's the best way to report this kind of stuff?

Individual tickets per-error on Ruby's Redmine installation:

https://bugs.ruby-lang.org/

I'm closing this, feel free to open any issue and mention me to discuss.

Cheers!

**Closed by luislavena** 2015-03-05 21:33 UTC

**Comment by Azolo** [comment] 2015-03-05 21:38
kk Thanks

I'll get started on the redesign next week sometime or soon after.
